// Code generated by "esc -o zzz_templates.go -pkg genphp templates"; DO NOT EDIT.

package genphp

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/templates/load.twig": {
		name:    "load.twig",
		local:   "templates/load.twig",
		size:    178,
		modtime: 1550935133,
		compressed: `
H4sIAAAAAAAC/4zMMQrCMBSH8T2n+C+hujQHqOCkIAgOHiCE9NU8SNOYZ6eQu0vtBZy+5eN3OueQVXIz
SXae8PSBZvcor0GpQu+VC9klecLIZbsOsPZ6u1+sxRE9OsPJm/XDsc8hd4OqGtNSMHEkcPpVoNt/lo9O
hMTUugOt7WrVoDRurm7qGwAA//9vm+rbsgAAAA==
`,
	},

	"/templates/structtypes.twig": {
		name:    "structtypes.twig",
		local:   "templates/structtypes.twig",
		size:    835,
		modtime: 1550935230,
		compressed: `
H4sIAAAAAAAC/3yRzW6cMBSF1/ZTnEpEMKgd9qGTdt1NF1l00VYjh7kEV2BbtpE6RX73yuAgQkbZWfbn
83Pv5y+mM1yJgZwRDeGx6WgQ3+1zzXlVYZrgr4bOEUAIcES4X29H2yME3vTCuTeoHExPAynv8Oub0+qR
rBS9/CeeesLEOTPjUy8bOC+8bJA1Wnn663FC3nlv7qvKzVmO2j7n9Rs8ekV2ZxvJ6Q6ttjDCkvKQKp0c
7gJnVVlyhhI/pO9grDZkvSSH1uohdljY4+3W28dUnqGsZktSl+gaPVKAVlJ/if7zYbVPr40e4nTOvVS0
Qsft7fIDZXR+RYfw2m+OkOaTTVOSSunrfboEtqNqvNQKfzbLoeKAiTOW6TFuQlgrrgVnjOVf035ynB5u
bejjQsXRLMh+MZyxQ83Ze8NhmXvJccEJTp9jtvN6WSDznXSfHvYdMSvLFgU+gAbjrwW2WgcsteZeP/P1
+yz/EvA3TttPUTEseTfDY5b8aBWiUM1Z4IH/DwAA//9Hj6RTQwMAAA==
`,
	},

	"/templates/util.twig": {
		name:    "util.twig",
		local:   "templates/util.twig",
		size:    611,
		modtime: 1550935292,
		compressed: `
H4sIAAAAAAAC/5yQwU7DMAyGz/FT+FCprTSeIGzwBhx2RKgKmUcztUkVO2iA9u6oaVcBA4S42t9n+/f1
zdAO4E1PPBhLuLUt9eYuPmmAffJWXPDIoTlw8A1TdKZzr1Rh8Wy6RFjjGyi3xwqpH+TlQz13VCRJ0WtQ
J5g5x42J0VyiRUiCa5yatQZQah8iGdsuqGEsnN/REdcbLKijnrzM+jS9J2nDrqGjY+FqYVZYjgG25/vL
ZatSeWEzJB73hCSrxbrafJKqGms9KiekjulHfblrgkHl8Cp5JqlG5L68tcELHaV8yND0pax/eVV4PJCV
v/zq2/jZ+iX8PGfiLuLqf51+ruSZGk7wHgAA//+TtlZQYwIAAA==
`,
	},

	"/templates": {
		name:  "templates",
		local: `templates`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"templates": {
		_escData["/templates/load.twig"],
		_escData["/templates/structtypes.twig"],
		_escData["/templates/util.twig"],
	},
}
