required = [
  "github.com/mjibson/esc",
]

[metadata]
tools = [
  "github.com/mjibson/esc",
]

[[constraint]]
  name = "github.com/mjibson/esc"
  version = "=0.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
