<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6b42fc6f594f7e1d8d924ad65a1e88d0
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\' => 55,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\' => 
        array (
            0 => __DIR__ . '/..' . '/dealerdirect/phpcodesniffer-composer-installer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6b42fc6f594f7e1d8d924ad65a1e88d0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6b42fc6f594f7e1d8d924ad65a1e88d0::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
